export interface EmployeeDetails {
    employeeId: number;		
    employeeType: string;		
    currentLocation: string;		
    firstName: string;		
    lastName: string;		
    baseBranch: string;		
    dob: string;		
    gender: string;		
    overallExp: number;		
    exp: number;		
    baseCountry: string;		
    baseDc: string;		
    categoryName: string;		
    grade: string;		
    createdAt: string;		
    status: string;
    empFullName?:string;
    projectId:string;
    projectName:string;
    projectLocation:string;
    projectChangeDate:string;
    workGeography:string;
    workCountry:string;
    workLocation:string;
    clientGeography:string;
    clientCountry:string;
    customer:string;
    groupCustomer:string;
    projectHash:string;
    projectLocationWrtIndia:string;
    projectType:string;
    pureTurnkeyFlag:string;
    swonCategory:string;
    projectCluster:string;
    iou:string;
    subIou:string;
    parentIou:string;
    childIou:string;
    bfsCluster:string;
    portfolioId:string;
    portfolioName:string;
    portfolioType:string;
    brmEmpId:string;
    onsiteLeadEmpId:string;
    dmEmpId:string;
    offshoreLeadEmpId:string;
    billingEmpId:string;
    description:string;
    id:string;
    won:string;
    startDate:string;
    endDate:string;
    travelType:string;
    employeeTravelCountry:string;
    teamRole:string;
    employeeActiveClientInd:string;
    deputeBranch:string;
    deputeDc:string;
    employeeLocationId:string;
    
}